lanuage: python
python:
    - "3.6"
cache: pip
before install:
    - pip install -U
    - pip install Cython
    - pip install -r requirements.txt
    - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
    - python setup.py install
script:
    - python examples/load_data.py
