dist: bionic
sudo: true
before_install:
    - pip install --upgrade pip
    - pip3 install -r requirements.txt
install:
    - python3 setup.py build develop
script:
    - python3 examples/load_data.py
