dist: bionic
sudo: true
language: python
before_install:
    - python --version
    - pip install --upgrade pip
    - pip install --upgrade cython
    - pip install -r requirements.txt
install:
    - python setup.py build develop
script:
    - python examples/load_data.py
