lanuage: python
python:
    - "3.6"
cache: pip
before install:
    #- pip install -U
    #- "export PYTHONPATH=$PYTHONPATH:$(pwd)"
    - pip install Cython
    - pip install -r requirements.txt
install:
    - python setup.py install
script:
    - python examples/load_data.py
